Charles Tyrwhitt/Patients.MVC/ViewModels/AllPatientsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CTPatients.MVC.ViewModels
{
    using CTPatients.Model;

    public class AllPatientsViewModel
    {
        public IEnumerable<PatientViewModel> Patients { get; set; }
    }
}

Charles Tyrwhitt/Patients.MVC/ViewModels/Mappers/IDomainViewModelMapper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CTPatients.MVC.ViewModels.Mappers
{
    public interface IDomainViewModelMapper< in TDomain, out TViewModel>
    {
        TViewModel Map(TDomain model);
    }
}

Charles Tyrwhitt/Patients.MVC/ViewModels/Mappers/IViewModelDomainMapper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CTPatients.MVC.ViewModels.Mappers
{
    public interface IViewModelDomainMapper<in TViewModel, out TDomain>
    {
        TDomain Map(TViewModel model);
    }
}

Charles Tyrwhitt/Patients.MVC/ViewModels/Mappers/PatientModelMapper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CTPatients.MVC.ViewModels.Mappers
{
    using CTPatients.Model;

    public class PatientModelMapper : IDomainViewModelMapper<Patient, PatientViewModel>
    {
        public PatientViewModel Map(Patient model)
        {
            return new PatientViewModel()
                       {
                           Name = model.Name,
                           Surname = model.Surname,
                           DateOfBirth = model.DateOfBirth.ToString("yyyy'-'MM'-'dd"),
                           Note = model.Note
                       };
        }
    }
}

Charles Tyrwhitt/Patients.MVC/ViewModels/Mappers/PatientViewModelMapper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CTPatients.MVC.ViewModels.Mappers
{
    using CTPatients.Model;

    public class PatientViewModelMapper : IViewModelDomainMapper<PatientViewModel, Patient>
    {
        public Patient Map(PatientViewModel model)
        {
            return new Patient
                              {
                                  Name = model.Name,
                                  Surname = model.Surname,
                                  DateOfBirth = DateTime.Parse(model.DateOfBirth),
                                  Note = model.Note
                              };
        }
    }
}

Charles Tyrwhitt/Patients.MVC/ViewModels/Mappers/PatientsViewModelMapper.cs
using CTPatients.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CTPatients.MVC.ViewModels.Mappers
{
    public class PatientsViewModelMapper : IDomainViewModelMapper<IEnumerable<Patient>, AllPatientsViewModel> 
    {
        public AllPatientsViewModel Map(IEnumerable<Patient> model)
        {
            return new AllPatientsViewModel()
            {
                Patients = model.Select(a => new PatientViewModel
                               {
                                   Name = a.Name,
                                   Surname = a.Surname,
                                   DateOfBirth = a.DateOfBirth.Date.ToString("yyyy'-'MM'-'dd"),
                                   Note = a.Note
                               }).AsEnumerable()
            };
        }
    }
}

Charles Tyrwhitt/Patients.MVC/ViewModels/PatientViewModel.cs
using System;

namespace CTPatients.MVC.ViewModels
{
    using System.ComponentModel.DataAnnotations;

    using CTPatients.MVC.ViewModelValidator;

    [UniquePatient]
    public class PatientViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please Enter A Name")]
        [DataType(DataType.Text)]
        [Display(Name = "Name")]
        [MinLength(2, ErrorMessage = "Name must be 2 or more characters")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please Enter A Surname")]
        [DataType(DataType.Text)]
        [Display(Name = "Surname")]
        [MinLength(3, ErrorMessage = "Surname must be 3 or more characters")]
        public string Surname { get; set; }

        [Required(ErrorMessage = "Please Enter A Date of Birth")]
        [DataType(DataType.Date, ErrorMessage = "Please enter a date of birth")]
        [Display(Name = "Date of Birth")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "yyyy'-'MM'-'dd")]
        [RegularExpression("^(19|20)[0-9][0-9]-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$", ErrorMessage = "Invalid date format - date of birth needs to be in format yyyy-mm-dd")]
        public string DateOfBirth { get; set; }

        [DataType(DataType.MultilineText)]
        public string Note { get; set; }
    }
}

Charles Tyrwhitt/Patients.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CTPatients.MVC.Controllers
{
    using CTPatients.MVC.ViewModels;
    using CTPatients.MVC.ViewModels.Mappers;
    using CTPatients.Model;
    using CTPatients.Services;

    public class HomeController : Controller
    {
        private readonly IPatientService patientService;
        private readonly IDomainViewModelMapper<IEnumerable<Patient>, AllPatientsViewModel> patientsViewModelMapper;

        public HomeController(IPatientService patientService,             
                        IDomainViewModelMapper<IEnumerable<Patient>, AllPatientsViewModel> patientsViewModelMapper)
        {
            this.patientService = patientService;
            this.patientsViewModelMapper = patientsViewModelMapper;
        }

        public ActionResult Index()
        {
            var viewModel = patientsViewModelMapper.Map(patientService.GetAllPatients());

            return View(viewModel);
        }
    }
}

Charles Tyrwhitt/Patients.MVC/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CTPatients.MVC.Controllers
{
    using CTPatients.MVC.ViewModels;
    using CTPatients.MVC.ViewModels.Mappers;
    using CTPatients.Model;
    using CTPatients.Services;

    public class PatientController : Controller
    {
        private readonly IPatientService patientService;
        private readonly IViewModelDomainMapper<PatientViewModel, Patient> patientViewModelDomainMapper;

        public PatientController(
            IPatientService patientService, 
            IViewModelDomainMapper<PatientViewModel, Patient> patientViewModelDomainMapper)
        {
            this.patientService = patientService;
            this.patientViewModelDomainMapper = patientViewModelDomainMapper;
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(PatientViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var patient = patientViewModelDomainMapper.Map(viewModel);
                patientService.AddPatient(patient);

                return RedirectToAction("Index", "Home");
            }

            return View(viewModel);
        }

    }
}

Charles Tyrwhitt/Patients.MVC/Views/Home/Index.cshtml
@model CTPatients.MVC.ViewModels.AllPatientsViewModel

@{
    ViewBag.Title = "Patient List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.Title.</h1>

<div>
    <table>
        <thead>
            <tr>
                <th>
                    Name
                </th>   
                <th>
                    Surname
                </th> 
                <th>
                    Birth Date
                </th>
                <th>
                    Note
                </th>
            </tr>
        </thead>
        <tbody>
        @foreach (var patient in Model.Patients)
        {
            <tr>
                <td>@patient.Name</td>
                <td>@patient.Surname</td>
                <td>@patient.DateOfBirth</td>
                <td>@patient.Note</td>
            </tr>
        }

        </tbody>
    </table>
    

</div>

Charles Tyrwhitt/Patients.MVC/Views/Patient/Add.cshtml
@model CTPatients.MVC.ViewModels.PatientViewModel

@{
    ViewBag.Title = "Add New Patient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
</hgroup>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <fieldset>
        <legend>Patient Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.Name)
                @Html.TextBoxFor(m => m.Name)
            </li>
            <li>
                @Html.LabelFor(m => m.Surname)
                @Html.TextBoxFor(m => m.Surname)
            </li>
            <li>
                @Html.LabelFor(m => m.DateOfBirth)
                @Html.TextBoxFor(m => m.DateOfBirth)
            </li>
            <li>
                @Html.LabelFor( m => m.Note)
                @Html.TextAreaFor( m => m.Note )
            </li>

        </ol>
        <input type="submit" value="Save" />
    </fieldset>
}

Charles Tyrwhitt/Patients.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - CT Patients</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("CT Patients", "Index", "Home")</p>
                </div>                
                <div class="float-right">
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("New Patient", "Add", "Patient")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - CT Patients</p>
                </div>
            </div>
        </footer>
        
        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
    <script type="text/javascript">
        @RenderSection("javascript", required: false)
    </script>
</html>